### PR TITLE
Validate amount parameter

### LINKED ISSUE #522: `send_payment` throws an error if amount_sats and bolt11 amount_msat is set
```
sdk> send_payment lnbc210n1pjje6axpp5lwnk3d6m75av86fdh6rpsnnmajuczyjvrprvlyeqdwp3e46am74qdqqcqzzsxqrrssrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwpapyqqqqqqq005qqqqlgqqqqqqgq9qsp5hlx2z9egv2xft3czlzx7gpruh4erngeq9v7tda0sg05ruuuy8vts9qyyssqwnvt8vlmxkwdlz85nsuvp84wg0mxl2z7z8q0z89ej9m4cwrhshlpmy8z9g3nrzpzqje5cr4gv8tgurx9xsh5g6vtvudmeelmkg5wrkcpmdzy9t -a 21
```
```
Error: Failed to send payment: status: Unknown, message: "Error calling method Pay: RpcError { code: Some(-32602), message: \"msatoshi parameter unnecessary\" }", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Mon, 16 Oct 2023 07:53:10 GMT", "content-length": "0"} }
```

### PR DESCRIPTION
**Pull request by roeierez**
fixed #522

### CODE REVIEW

File: libs/sdk-core/src/breez_services.rs [hunk 1]
```diff
@@ -235,6 +235,23 @@ impl BreezServices {
...
+
+        // Ensure amount is provided for zero invoice
+        if provided_amount_msat == 0 && invoice_amount_msat == 0 {
+            return Err(SdkError::SendPaymentFailed {
+                err: "amount must be provided when paying a zero invoice".into(),
+            });
+        }
+
+        // Ensure amount is not provided for invoice that contains amount
+        if provided_amount_msat > 0 && invoice_amount_msat > 0 {
```
Comment (dangeross) [inline libs/sdk-core/src/breez_services.rs:249]: Should we consider allowing if non-zero amounts match?

Comment (roeierez) [reply libs/sdk-core/src/breez_services.rs:249]: I think it is better to be strict here. Greenlight doesn't allow it even if matches.

File: libs/sdk-core/src/breez_services.rs [hunk 2]
```diff
@@ -235,6 +235,23 @@ impl BreezServices {
     ) -> SdkResult<Payment> {
         self.start_node().await?;
         let parsed_invoice = parse_invoice(bolt11.as_str())?;
+        let invoice_amount_msat = parsed_invoice.amount_msat.unwrap_or_default();
+        let provided_amount_msat = amount_sats.unwrap_or_default() * 1000;
```
Comment (JssDWt) [inline libs/sdk-core/src/breez_services.rs:239]: Maybe this is a good time to change the method signature to amount_msat? I think we'd want to do that anyway?

File: libs/sdk-core/src/breez_services.rs (hunk 1 above)
Comment (JssDWt) [reply libs/sdk-core/src/breez_services.rs:249]: I think we should. If the amounts match, we should ignore the provided amount. Because the method signature takes an amount parameter, you expect you have to pass an amount there. Developers will have already parsed the invoice to show the amount to the user. So they already have the amount in a variable. It makes sense to pass it here. But that only really works if the input parameter is in millisatoshi, otherwise it only works full full satoshi amounts.

Comment (JssDWt) [reply libs/sdk-core/src/breez_services.rs:249]: Ah, Roei's comment wasn't there yet when I answered. No strong opinion tbh.

Comment (roeierez) [reply libs/sdk-core/src/breez_services.rs:249]: The fact the amount is parsed in the invoice doesn't necessary mean it is required in the `send_payment` and the signature takes optional amount.
Don't you think it feels weird to allow passing a parameter only in the case it is actually redundant? I mean how would we document such behavior? "Amount is allowed if it is the same as in the invoice"?
It would make sense IMO if the node supports passing amount that is greater or equal to the invoice amount but this is not the case here.
Isn't it more coherent (and clear to the user) behavior to require (and allow) amount only in case of zero invoice and avoid this redundancy?
What do you think?

Comment (roeierez) [reply libs/sdk-core/src/breez_services.rs:249]: @JssDWt comments wasn't there when I answered :)
Anyway let me know your final thoughts.

Comment (JssDWt) [reply libs/sdk-core/src/breez_services.rs:249]: @roeierez Yeah makes sense. We were getting quite a few questions about this particular issue. I think the error is much better now and should probably lead to less questions already. Maybe make it clearer in the docs too.

Comment (ok300) [reply libs/sdk-core/src/breez_services.rs:249]: How about supporting both with `SendPaymentRequest` and `SendPaymentZeroAmountInvoice`?

Comment (ok300) [reply libs/sdk-core/src/breez_services.rs:249]: Nevermind, that would complicate the service interface for very little benefit.

I agree with @JssDWt above.

File: libs/sdk-core/src/breez_services.rs (hunk 2 above)
Comment (ok300) [reply libs/sdk-core/src/breez_services.rs:239]: I agree, changing to `msat` is a step towards #417.

Comment (roeierez) [reply libs/sdk-core/src/breez_services.rs]: I agree with both of you. I did change this method signature to msat. Not all other methods.
I think we have 2 more methods where we should change (I am not sure the onchain methods should use msat).
I suggest to do it in a separate PR.

File: libs/sdk-core/src/breez_services.rs [hunk 3]
```diff
@@ -1185,12 +1202,12 @@ impl BreezServices {
...
             .parse_filters(
                 r#"
-                info,
+                debug,
                 breez_sdk_core::input_parser=warn,
                 breez_sdk_core::backup=info,
                 breez_sdk_core::persist::reverseswap=info,
                 breez_sdk_core::reverseswap=info,
-                gl_client=warn,
+                gl_client=debug,
```
Comment (dangeross) [inline libs/sdk-core/src/breez_services.rs:1210]: Did you mean to include log filter changes?

**Review by JssDWt — APPROVED** [review]
LGTM!

**Review by dangeross — APPROVED** [review]
Looks good. Just a comment about log filters below. As you're changing the send_payment interface, you could also move to a SendPaymentRequest struct

File: libs/sdk-core/src/breez_services.rs (hunk 3 above)
Comment (roeierez) [reply libs/sdk-core/src/breez_services.rs:1210]: Good catch! Actually I didn't but I find myself always change that when I need to debug, I think we can push this change as it enables logging the signer and gl-client node logs.
What do you think?

Comment (dangeross) [reply libs/sdk-core/src/breez_services.rs:1210]: 👍  just making sure

**Review by ok300 — APPROVED** [review]
